{{header}}

TWICE = true

include sylex.conf
override SPECS = $(DOC:%={{build}}/pdf_%.tex.mk)

override BUILDER = python3 .sylex/sylex.py

all: $(SPECS) $(DOC:%=%.pdf)

{{build}}/common.tex.mk:
    $(BUILDER) build-aux --common

{{build}}/pdf_%.tex.mk: cfg_%.slx
    $(BUILDER) build-conf --proj $* --level WARNING

include {{build}}/common.tex.mk
include $(SPECS)

clean: $(DOC:%=clean_%)
    rm -rf {{build}}

TARGET = all
force:
    make clean
    make $(TARGET)

.PHONY: clean force

