{{header}}

TWICE = true

include sylex.conf
SPECS = $(DOC:%={{build}}/pdf_%.tex.mk)

BUILDER = python3 .sylex/sylex.py

all: $(SPECS) $(DOC:%=%.pdf)

{{build}}/common.tex.mk:
    $(BUILDER) build-aux --common

{{build}}/pdf_%.tex.mk: cfg_%.slx
    $(BUILDER) build-conf --proj $* --level WARNING

include {{build}}/common.tex.mk
include $(SPECS)

clean:
    rm -rf {{build}}
    rm -f $(DOC:%=%.pdf)
    rm -f texwatch

TARGET = all
force:
    make clean
    make $(TARGET)

.PHONY: clean force

